[package]
name = "cargo-fluent"
version = "1.0.0"
edition = "2018"
description = "Cargo Tool for Fluent internationalization system"

[dependencies]
toml = "~0.5.8"
libc = "~0.2.117"
poreader = "~1.0.6"
serde = { version = "~1.0.136", features = ["std", "serde_derive"] }
syn = { version = "~1.0.86", features = ["full"] }
clap = { version = "~2.33.4", features = ["wrap_help"] }
iced = { version = "~0.3.0", features = ["default", "image", "svg", "tokio"] }
